### ISSUE TITLE
ToDo: Unit Testing and Continuos Integration

### ISSUE THREAD

**Issue by foehnx** [uzh-rpg/vilib#2]
Enabling continuous integration checks through unit tests should help with various possible bugs.
This issue might take a while to be implemented and resolved.
It will require testing on a CUDA enabled Jenkins machine or similar.

- [ ] Create unit tests within [GoogleTest](https://github.com/google/googletest)
- [ ] Create simpler cmake for building
- [ ] Setup our Jenkins and webhooks.
- [ ] Deploy CI by requiring successful tests for a pull request merge.
